import Head from "next/head";
import { Montserrat } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

const Mon = Montserrat({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>NewsArena</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${Mon.className}`}>
        {" "}
        <div>
          <h1>News Arena Website</h1>
          <h2>Coming soon ......</h2>
          <Link href="/dashboard/home">GoTo HomePage</Link>
        </div>
      </main>
    </>
  );
}
